export const workoutInfo = {
  goals: [
    { title: "Fat loss", change: 2 },
    { title: "Weight loss", change: 4 },
  ],
  muscle_groups: ["Chest", "Triceps"],
  workouts: {
    warmup: [
      {
        id: 10,
        title: "Halos Right & Left",
        rep_name: "Rotations",
        reps: 15,
        type: "Stretching",
        weight_kg: 10,
        order: 1,
      },
      {
        id: 10,
        title: "Internal Rotations",
        reps: 15,
        weight_kg: 10,
        order: 2,
      },
      {
        id: 10,
        title: "External Rotations",
        reps: 15,
        weight_kg: 10,
        order: 3,
      },
      {
        id: 10,
        title: "Pushups",
        reps: 15,
        weight_kg: 10,
        order: 4,
      },
      {
        id: 10,
        title: "Halos Right & Left",
        rep_name: "Rotations",
        reps: 15,
        type: "Stretching",
        weight_kg: 10,
        order: 1,
      },
      {
        id: 10,
        title: "Internal Rotations",
        reps: 15,
        weight_kg: 10,
        order: 2,
      },
      {
        id: 10,
        title: "External Rotations",
        reps: 15,
        weight_kg: 10,
        order: 3,
      },
      {
        id: 10,
        title: "Pushups",
        reps: 15,
        weight_kg: 10,
        order: 4,
      },
      {
        id: 10,
        title: "Halos Right & Left",
        rep_name: "Rotations",
        reps: 15,
        type: "Stretching",
        weight_kg: 10,
        order: 1,
      },
      {
        id: 10,
        title: "Internal Rotations",
        reps: 15,
        weight_kg: 10,
        order: 2,
      },
      {
        id: 10,
        title: "External Rotations",
        reps: 15,
        weight_kg: 10,
        order: 3,
      },
      {
        id: 10,
        title: "Pushups",
        reps: 15,
        weight_kg: 10,
        order: 4,
      },
    ],
  },
};
